name: 'Publish to npm'
description: 'Publish the release to npm'
inputs:
  npm-token:
    description: 'The token used for npm publishing. If omitted the action will perform a dry run npm publish.'
    required: false

runs:
  using: 'composite'
  steps:
    - id: Publish
      shell: bash
      run: ${{ github.action_path }}/scripts/main.sh
      env:
        YARN_NPM_AUTH_TOKEN: ${{ inputs.npm-token }}
