name: 'Publish to npm'
description: 'Publish the release to npm'
inputs:
  npm-token:
    description: 'The token used for npm publishing. If omitted the action will perform a dry run npm publish.'
    required: false
  npm-tag:
    description: 'The npm tag to publish to. Defaults to "latest".'
    required: false
    default: 'latest'
  slack-webhook-url:
    description: 'Slack Webhook URL'
    required: false

runs:
  using: 'composite'
  steps:
    - id: Publish
      shell: bash
      run: ${{ github.action_path }}/scripts/main.sh
      env:
        YARN_NPM_AUTH_TOKEN: ${{ inputs.npm-token }}
        PUBLISH_NPM_TAG: ${{ inputs.npm-tag }}
    - id: name-version
      shell: bash
      if: inputs.slack-webhook-url != ''
      run: |
        TEXT=$(jq --raw-output '.name + "@" + .version' package.json )
        TEXT_STRIPPED="${TEXT#@}"
        echo "NAME_VERSION=$TEXT_STRIPPED" >> "$GITHUB_OUTPUT"
    - name: Post to a Slack channel
      id: slack
      if: inputs.slack-webhook-url != ''
      uses: slackapi/slack-github-action@007b2c3c751a190b6f0f040e47ed024deaa72844
      with:
        payload: |
          {
            "icon_url": "https://raw.githubusercontent.com/MetaMask/action-npm-publish/main/robo.svg",
            "text": "`${{ steps.name-version.outputs.NAME_VERSION }}` is awaiting deployment :rocket: : https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "`${{ steps.name-version.outputs.NAME_VERSION }}` is awaiting deployment :rocket: \n <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/|→ Click here to review deployment>"
                }
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.slack-webhook-url }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
