#!/usr/bin/env bash

# Yarn runs code from the repository: plugins listed in `.yarnrc.yml`, a
# `yarnPath` release, and lifecycle scripts during `yarn pack` and
# `yarn npm publish`. This script runs before any Yarn command that publishes,
# and removes the repository's ability to run code that way:
#
# 1. Yarn is pointed to a minimal configuration file, which is stored outside
#    of the checkout under a random name, so it can't be shadowed by a file in
#    the repository. The repository's own `.yarnrc.yml` is never loaded.
# 2. The user-level `~/.yarnrc.yml` is removed, because Yarn always loads it,
#    and it can also list plugins.
# 3. Lifecycle scripts are removed from every package that may be published.
# 4. Packages that redirect publishing to a registry other than
#    `https://registry.npmjs.org` are rejected.

set -e
set -o pipefail

if [ "$RUNNER_DEBUG" = "1" ]; then
  set -x
fi

script_path=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )

# shellcheck source=scripts/environment.sh
source "$script_path/environment.sh"

rc_filename=".yarnrc-$(openssl rand -hex 16).yml"
rc_path="$(dirname "$PWD")/$rc_filename"
cat > "$rc_path" <<'EOF'
# Generated by MetaMask/action-npm-publish.
enableScripts: false
enableTelemetry: false
injectEnvironmentFiles: []
nodeLinker: node-modules
npmPublishRegistry: "https://registry.npmjs.org"
npmRegistryServer: "https://registry.npmjs.org"
EOF

export YARN_RC_FILENAME="$rc_filename"

if [[ -n "$GITHUB_ENV" ]]; then
  echo "YARN_RC_FILENAME=$rc_filename" >> "$GITHUB_ENV"
fi

rm -f "$HOME/.yarnrc.yml"

# The workspace list is read with the empty configuration above, so no code
# from the repository is loaded. In a polyrepo, the root is the only workspace.
locations=$(yarn workspaces list --json --no-private | jq --raw-output '.location')

while read -r location; do
  [[ -z "$location" ]] && continue

  manifest="$location/package.json"

  registry=$(jq --raw-output '.publishConfig.registry // empty' "$manifest")
  if [[ -n "$registry" && "${registry%/}" != "https://registry.npmjs.org" ]]; then
    echo "::error::\"$manifest\" sets \"publishConfig.registry\" to \"$registry\". Only \"https://registry.npmjs.org\" is supported."
    exit 1
  fi

  sanitized=$(jq 'del(.scripts.prepublish, .scripts.prepublishOnly, .scripts.prepack, .scripts.postpack)' "$manifest")
  echo "$sanitized" > "$manifest"
done <<< "$locations"

echo "Notice: Yarn configuration and lifecycle scripts sanitized."
