name: Shellcheck

permissions:
  checks: write

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run shellcheck
        uses: fearphage/shellcheck-action@95d2a3d34d381a7314c286ea1725ca8cce3b51fd
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
