name: Test publish (polyrepo)
on:
  push:
    branches: [main]
  pull_request:
jobs:
  # Test npm publish dry-run.
  checkout-publish-utils-dry-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout utils repository
        uses: actions/checkout@v6
        with:
          repository: MetaMask/utils
          ref: v11.8.1
          path: utils
      - name: Checkout action repository
        uses: actions/checkout@v6
        with:
          path: action-npm-publish
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24
      - name: Setup, Build, Publish
        shell: bash
        run: |
          cd utils
          yarn install --immutable
          yarn build
          ../action-npm-publish/scripts/main.sh
