name: Test publish (monorepo)

on:
  push:
    branches: [main]
  pull_request:

jobs:
  # Test npm publish dry-run.
  checkout-publish-skunkworks-dry-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Snaps repository
        uses: actions/checkout@v6
        with:
          repository: MetaMask/snaps-skunkworks
          ref: 2befb570c72fddd577410b0193982332eed0fc41
          path: skunkworks
      - name: Checkout action repository
        uses: actions/checkout@v6
        with:
          path: action-npm-publish
      - name: Setup, build, publish
        run: |
          cd skunkworks
          yarn install --immutable
          PUBLISH_NPM_TAG="latest" ../action-npm-publish/scripts/main.sh

  # Test that publishing is skipped when attempting to republish the latest
  # version.
  checkout-publish-skunkworks-skip:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest version from NPM
        id: latest-release
        run: echo "release-version=$(npm view MetaMask/snaps-skunkworks version --workspaces=false)" >> "$GITHUB_OUTPUT"
      - name: Checkout Snaps repository
        uses: actions/checkout@v6
        with:
          repository: MetaMask/snaps-skunkworks
          ref: v${{ steps.latest-release.outputs.release-version }}
          path: skunkworks
      - name: Checkout action repository
        uses: actions/checkout@v6
        with:
          path: action-npm-publish
      - name: Setup, build, publish
        run: |
          cd skunkworks
          yarn install --immutable
          PUBLISH_NPM_TAG="latest" NPM_TOKEN="test" ../action-npm-publish/scripts/main.sh
