name: Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and setup environment
        uses: MetaMask/action-checkout-and-setup@v3
        with:
          is-high-risk-environment: false
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test

  check-workflows:
    name: Check workflows
    runs-on: ubuntu-latest
    steps:
      - name: Download actionlint
        id: download-actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/914e7df21a07ef503a81201c76d2b11c789d3fca/scripts/download-actionlint.bash) 1.7.12
        shell: bash
      - name: Check workflow files
        env:
          ACTIONLINT_EXECUTABLE: ${{ steps.download-actionlint.outputs.executable }}
        run: |
          echo "::add-matcher::.github/actionlint-matcher.json"
          "$ACTIONLINT_EXECUTABLE" -color
        shell: bash

  all-jobs-completed:
    name: All jobs completed
    runs-on: ubuntu-latest
    needs:
      - test
      - check-workflows
    outputs:
      PASSED: ${{ steps.set-output.outputs.PASSED }}
    steps:
      - name: Set PASSED output
        id: set-output
        run: echo "PASSED=true" >> "$GITHUB_OUTPUT"

  all-jobs-pass:
    name: All jobs pass
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: all-jobs-completed
    steps:
      - name: Check that all jobs have passed
        run: |
          passed="${{ needs.all-jobs-completed.outputs.PASSED }}"
          if [[ $passed != "true" ]]; then
            exit 1
          fi
